#!/bin/bash

if [ "$(file -i /usr/bin/calamares | grep shellscript)" = "" ]; then
    mv -f /usr/bin/calamares /usr/bin/calamares-manjaro
    cp /usr/bin/calamares-biglinux /usr/bin/calamares
fi

rm -f /usr/share/applications/calamares.desktop
